name: deploy wordpress theme
  
on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  deploy:
  
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
 
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
      - name: rsync deploy
        run: rsync -auzrv --delete ./ xs445525@sv12589.xserver.jp:home/xs445525/tech-tech.blog/public_html/ --exclude ".git/" --exclude ".github/workflows"  -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
